# Generated by Django 5.1.4 on 2025-03-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_alter_reports_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='reports',
        ),
        migrations.CreateModel(
            name='reportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='analyze.reports')),
            ],
        ),
    ]
